[workspace]
members = ["archipelago_rs", "DMC3ArchipelagoClient", "DMCHDLoader", "randomizer_utilities"]
resolver = "3"

[profile.release]
lto = true

[workspace.dependencies]
windows = "0.62.2"
log = "0.4.28"
